#on:
#  push:
#    branches:
#      - main2

on:
  workflow_run:
    workflows: ["action1"]
    types:
      - completed


jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: Print Message
        run: echo "Hello, GitHub Actions! 22"