#on:
#  push:
#    branches:
#      - main2

on:
  workflow_run:
    workflows: ["action1"]
    types:
      - completed


jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'main2'

      - name: Print Message
        run: echo "Hello, GitHub Actions! 22"

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Git branch
        run: |
          git branch


