name: Merge

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Merge to main2
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout main2
          git merge --allow-unrelated-histories main --no-ff --no-edit
          git push origin main2
